# Generated by Django 2.2.6 on 2020-05-07 12:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('surname', models.CharField(help_text='Surname', max_length=50)),
                ('other_name', models.CharField(help_text='Other Name', max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('name_of_father', models.CharField(blank=True, default='None', help_text="Father's name", max_length=50)),
                ('name_of_mother', models.CharField(blank=True, default='None', help_text="Mother's name", max_length=50)),
                ('name_of_siblings', models.TextField(blank=True, default='None', help_text="Name of Brother's / Sister's")),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=15)),
                ('name_of_spouse', models.CharField(blank=True, default='None', help_text='Spouse name if any', max_length=50)),
                ('marriage_information', models.TextField(help_text='Leave Blank if Single')),
                ('state_of_origin', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Cross River'), ('Cross River', 'Cross River'), ('Delata', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=15)),
                ('LGA', models.CharField(help_text='Local Goverment Area', max_length=50)),
                ('state_of_residence', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Cross River'), ('Cross River', 'Cross River'), ('Delata', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=15)),
                ('residential_address', models.TextField(help_text='Home Address', max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('other_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('language_spoken', models.CharField(help_text='Language(s) spoken', max_length=350)),
                ('national_id', models.CharField(max_length=50)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('genotype', models.CharField(blank=True, choices=[('aa', 'AA'), ('as', 'AS'), ('ss', 'SS'), ('others', 'Others: CC, AC..')], max_length=3, null=True)),
                ('disability', models.TextField(default='None', help_text='Specify disability and cause and time of disablity \n e.g Blindess-Car Accident 2012')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('primary_education', models.TextField(default='None', help_text='Nigerian Primary School - (2000-2009)')),
                ('secondary_education', models.TextField(default='None', help_text='Nigerian Secondary School - (2009-2015)')),
                ('academic_qualifications', models.TextField(default='None', help_text='Bsc - Nigerian University(2020)')),
                ('occupation', models.CharField(help_text='Pilot', max_length=250)),
                ('work_experience', models.TextField(help_text='Worked as a Consultant at Shell (2021-2023)')),
            ],
        ),
    ]
