# Generated by Django 2.2.6 on 2020-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='residential_address',
            field=models.CharField(help_text='Home Address', max_length=500),
        ),
    ]
