# Generated by Django 2.2.6 on 2020-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0002_auto_20200507_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='disability',
            field=models.CharField(default='None', help_text='Specify disability and cause and time of disablity \n e.g Blindess-Car Accident 2012', max_length=1000),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name_of_siblings',
            field=models.CharField(blank=True, default='None', help_text="Name of Brother's / Sister's", max_length=1250),
        ),
    ]
