# Generated by Django 2.2.6 on 2020-05-15 12:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0004_auto_20200514_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='image',
            field=models.ImageField(default='/images/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='images'),
        ),
    ]
