# Generated by Django 2.2.6 on 2020-05-15 13:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0005_citizen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
    ]
