# Generated by Django 2.2.6 on 2020-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0006_auto_20200515_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
