# Generated by Django 2.2.6 on 2020-05-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisdb', '0008_auto_20200515_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='number_of_children',
        ),
    ]
